"""
SQLAlchemy models for normalized OpenAPI spec storage with bitemporal columns.

Transaction time (sys_from/sys_to): when a row entered/left our database.
  - For HTTP scrapes: wall-clock time of the scrape.
  - For git-based scrapes: the git commit timestamp.
  - Managed automatically — sys_from defaults to now(), sys_to=NULL means current.

Valid time (source_updated_at on ApiSpec): when the spec actually changed
  upstream, per the registry's own metadata. Not on every table — only
  ApiSpec carries it, since lower-level tables inherit provenance from
  their parent spec.

Targets: SQLite, DuckDB, PostgreSQL, SQL Server.

Dialect notes:
  - JSON columns: native on SQLite/DuckDB/PG, rendered as NVARCHAR(MAX) on
    SQL Server via type_compilation_extension.
  - Text columns used in indexes are bounded (String(500)) on SQL Server
    to stay within index key size limits.
"""

from datetime import datetime, timezone

from sqlalchemy import JSON, Boolean, DateTime, Float, ForeignKey, Identity, Index, Integer, String, Text, UniqueConstraint, event
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


def _identity_pk(**kwargs):
    """
    Primary key column that works across all 4 dialects.

    DuckDB's duckdb-engine 0.17 renders autoincrement as SERIAL (removed
    in DuckDB 1.x) and can't combine GENERATED BY DEFAULT AS IDENTITY
    with UNIQUE constraints in the same CREATE TABLE. We use Identity()
    which works on PG, SQL Server, and DuckDB (when no UNIQUE constraints
    coexist). SQLite ignores Identity() and uses ROWID autoincrement.
    """
    return mapped_column(Integer, Identity(), primary_key=True, **kwargs)


class Base(DeclarativeBase):
    pass


# ---------------------------------------------------------------------------
# Temporal mixin
# ---------------------------------------------------------------------------

class TemporalMixin:
    """
    Transaction-time (SYSTEM_TIME) columns for all normalized tables.

    These track when a row was current in *our* database, not when the
    upstream fact was true. sys_from is set when the row is inserted;
    sys_to is set when a newer version supersedes it (NULL = current).
    """

    sys_from: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
    sys_to: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        doc="NULL means current version",
    )


# ---------------------------------------------------------------------------
# Registry: where we discovered the spec (APIs.guru, SwaggerHub, etc.)
# ---------------------------------------------------------------------------

class ApiRegistry(TemporalMixin, Base):
    """A source registry from which we scrape API specs."""

    __tablename__ = "api_registry"

    registry_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    name: Mapped[str] = mapped_column(String(200), unique=True)
    base_url: Mapped[str] = mapped_column(Text)
    registry_type: Mapped[str] = mapped_column(
        String(50), doc="apis_guru | swaggerhub | custom"
    )

    specs: Mapped[list["ApiSpec"]] = relationship(back_populates="registry")


# ---------------------------------------------------------------------------
# Spec-level: one row per API (provider + API name)
# ---------------------------------------------------------------------------

class ApiSpec(TemporalMixin, Base):
    """
    One row per API identity (e.g. 'petstore' from provider 'swagger.io').
    The spec_version tracks the OpenAPI document version string, not our
    internal versioning — temporal columns handle that.
    """

    __tablename__ = "api_spec"

    spec_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    registry_id: Mapped[int | None] = mapped_column(
        ForeignKey("api_registry.registry_id"), nullable=True
    )
    provider: Mapped[str] = mapped_column(String(200))
    api_name: Mapped[str] = mapped_column(String(200))
    spec_version: Mapped[str | None] = mapped_column(String(50), nullable=True)
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    base_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    openapi_version: Mapped[str | None] = mapped_column(
        String(20), nullable=True, doc="e.g. '3.0.3', '3.1.0'"
    )
    source_url: Mapped[str | None] = mapped_column(
        Text, nullable=True, doc="URL where we fetched the spec document"
    )
    source_updated_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        doc="Timestamp from the registry (e.g. apis.guru 'updated' field)",
    )
    raw_spec: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, doc="Full spec document for reference"
    )

    __table_args__ = (
        UniqueConstraint("provider", "api_name", "sys_from", name="uq_spec_identity"),
        Index("ix_spec_provider_api", "provider", "api_name"),
    )

    registry: Mapped[ApiRegistry | None] = relationship(back_populates="specs")
    paths: Mapped[list["ApiPath"]] = relationship(back_populates="spec")
    schemas: Mapped[list["ApiSchema"]] = relationship(back_populates="spec")


# ---------------------------------------------------------------------------
# Paths: /users, /users/{id}, etc.
# ---------------------------------------------------------------------------

class ApiPath(TemporalMixin, Base):
    """One row per path string within a spec."""

    __tablename__ = "api_path"

    path_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    spec_id: Mapped[int] = mapped_column(ForeignKey("api_spec.spec_id"))
    path: Mapped[str] = mapped_column(
        String(500), doc="URL path — bounded for SQL Server index compatibility"
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_path_spec", "spec_id", "path"),
    )

    spec: Mapped[ApiSpec] = relationship(back_populates="paths")
    operations: Mapped[list["ApiOperation"]] = relationship(back_populates="path")


# ---------------------------------------------------------------------------
# Operations: GET /users, POST /users, etc.
# ---------------------------------------------------------------------------

class ApiOperation(TemporalMixin, Base):
    """One row per path + HTTP method."""

    __tablename__ = "api_operation"

    operation_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    path_id: Mapped[int] = mapped_column(ForeignKey("api_path.path_id"))
    method: Mapped[str] = mapped_column(String(10), doc="get, post, put, delete, etc.")
    operation_name: Mapped[str | None] = mapped_column(
        String(200), nullable=True, doc="operationId from the spec"
    )
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    deprecated: Mapped[bool] = mapped_column(Boolean, default=False)
    tags: Mapped[dict | None] = mapped_column(JSON, nullable=True)

    __table_args__ = (
        Index("ix_op_path_method", "path_id", "method"),
    )

    path: Mapped[ApiPath] = relationship(back_populates="operations")
    parameters: Mapped[list["ApiParameter"]] = relationship(back_populates="operation")
    responses: Mapped[list["ApiResponse"]] = relationship(back_populates="operation")


# ---------------------------------------------------------------------------
# Parameters: query, path, header, cookie params per operation
# ---------------------------------------------------------------------------

class ApiParameter(TemporalMixin, Base):
    """One row per parameter on an operation."""

    __tablename__ = "api_parameter"

    parameter_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    operation_id: Mapped[int] = mapped_column(ForeignKey("api_operation.operation_id"))
    name: Mapped[str] = mapped_column(String(200))
    location: Mapped[str] = mapped_column(
        String(20), doc="query | path | header | cookie"
    )
    required: Mapped[bool] = mapped_column(Boolean, default=False)
    schema_json: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, doc="Parameter schema (type, format, enum, etc.)"
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_param_op", "operation_id", "name"),
    )

    operation: Mapped[ApiOperation] = relationship(back_populates="parameters")


# ---------------------------------------------------------------------------
# Responses: status codes and their schemas per operation
# ---------------------------------------------------------------------------

class ApiResponse(TemporalMixin, Base):
    """One row per status code on an operation."""

    __tablename__ = "api_response"

    response_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    operation_id: Mapped[int] = mapped_column(ForeignKey("api_operation.operation_id"))
    status_code: Mapped[str] = mapped_column(
        String(10), doc="200, 201, default, etc."
    )
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    media_type: Mapped[str | None] = mapped_column(
        String(100), nullable=True, doc="e.g. application/json"
    )
    schema_json: Mapped[dict | None] = mapped_column(
        JSON, nullable=True, doc="Response body schema"
    )

    __table_args__ = (
        Index("ix_resp_op", "operation_id", "status_code"),
    )

    operation: Mapped[ApiOperation] = relationship(back_populates="responses")


# ---------------------------------------------------------------------------
# Component schemas: reusable $ref targets
# ---------------------------------------------------------------------------

class ApiSchema(TemporalMixin, Base):
    """
    One row per named schema in components/schemas.
    Stored as JSON — decomposing further into properties is diminishing returns.
    """

    __tablename__ = "api_schema"

    schema_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    spec_id: Mapped[int] = mapped_column(ForeignKey("api_spec.spec_id"))
    schema_name: Mapped[str] = mapped_column(String(200))
    schema_json: Mapped[dict] = mapped_column(JSON)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        Index("ix_schema_spec", "spec_id", "schema_name"),
    )

    spec: Mapped[ApiSpec] = relationship(back_populates="schemas")


# ---------------------------------------------------------------------------
# Staging table: fast metadata-only catalog from git tree walk
# ---------------------------------------------------------------------------

class GitSpecStaging(Base):
    """
    Tier 1 catalog: metadata extracted via regex from git blob headers.
    No YAML parse — just tree walk + regex on raw bytes.
    blob_sha is the pointer back to git for on-demand content retrieval.
    """

    __tablename__ = "git_spec_staging"

    staging_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    commit_sha: Mapped[str] = mapped_column(String(40))
    commit_ts: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    provider: Mapped[str] = mapped_column(String(200))
    api_name: Mapped[str] = mapped_column(String(200))
    file_path: Mapped[str] = mapped_column(String(500))
    blob_sha: Mapped[str] = mapped_column(String(40))
    title: Mapped[str | None] = mapped_column(Text, nullable=True)
    spec_version: Mapped[str | None] = mapped_column(String(100), nullable=True)
    openapi_version: Mapped[str | None] = mapped_column(String(20), nullable=True)

    __table_args__ = (
        UniqueConstraint("provider", "api_name", "blob_sha", name="uq_staging_identity"),
        Index("ix_staging_provider", "provider", "api_name"),
        Index("ix_staging_blob", "blob_sha"),
    )


# ---------------------------------------------------------------------------
# API adapter: JMESPath expressions for call construction + response reshaping
# ---------------------------------------------------------------------------

class ApiAdapter(TemporalMixin, Base):
    """
    JMESPath adapter for an API operation.

    Two expressions per operation:
      call_jmespath:     context object → {url, params}
      response_jmespath: response body → common schema

    Temporal: sys_from/sys_to track when this adapter version was current,
    enabling time-aware joins with the API spec it targets. When the spec
    changes shape, a new adapter version is inserted and the old one closed.

    Loaded from YAML files in adapters/ and stored in git alongside the specs.
    """

    __tablename__ = "api_adapter"

    adapter_id: Mapped[int] = mapped_column(Integer, Identity(), primary_key=True)
    provider: Mapped[str] = mapped_column(String(200))
    api_name: Mapped[str] = mapped_column(String(200))
    path: Mapped[str] = mapped_column(String(500))
    method: Mapped[str] = mapped_column(String(10))
    base_url: Mapped[str | None] = mapped_column(Text, nullable=True)
    vault_secret: Mapped[str | None] = mapped_column(
        String(200), nullable=True,
        doc="Key in OpenBao at secret/blobapi/{vault_secret}",
    )
    call_jmespath: Mapped[str] = mapped_column(Text)
    call_notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    response_jmespath: Mapped[str] = mapped_column(Text)
    response_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    __table_args__ = (
        UniqueConstraint("provider", "api_name", "path", "method", "sys_from",
                        name="uq_adapter_identity"),
        Index("ix_adapter_provider", "provider", "api_name"),
    )


# ---------------------------------------------------------------------------
# LLM adapter: inja prompt templates for LLM-backed reified functions
# ---------------------------------------------------------------------------

class LlmAdapter(Base):
    """
    Reified LLM function definition.

    Each row drives the llm_adapt() DuckDB macro: an inja prompt template,
    a JSON Schema for output validation, and a JMESPath expression to
    reshape the validated response.

    Session-scoped: lives in DuckDB/SQLite during a query session.
    Loaded from YAML files in adapters/ (those with prompt_template keys).
    """

    __tablename__ = "llm_adapter"

    name: Mapped[str] = mapped_column(String(200), primary_key=True)
    prompt_template: Mapped[str] = mapped_column(
        Text, doc="Inja/Jinja2 template, rendered with caller params"
    )
    output_schema: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="JSON Schema (Draft 2020-12) for response validation",
    )
    response_jmespath: Mapped[str | None] = mapped_column(
        Text, nullable=True,
        doc="JMESPath expression to reshape validated JSON",
    )
    max_tokens: Mapped[int] = mapped_column(Integer, default=4096)


# ---------------------------------------------------------------------------
# LLM pricing: per-model token costs (session-scoped reference table)
# ---------------------------------------------------------------------------

class LlmPricing(Base):
    """
    Per-model token pricing in USD per million tokens.

    Session-scoped: lives in DuckDB/SQLite, loaded from YAML or Bifrost.
    Used for cost accounting by joining against _meta from llm_adapt() results.
    """

    __tablename__ = "llm_pricing"

    model: Mapped[str] = mapped_column(String(200), primary_key=True)
    input_per_mtok: Mapped[float] = mapped_column(
        Float, doc="Standard input cost, USD per MTok"
    )
    output_per_mtok: Mapped[float] = mapped_column(
        Float, doc="Standard output cost, USD per MTok"
    )
    cache_write_5m_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="5-minute prompt cache write, USD per MTok"
    )
    cache_write_1h_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="1-hour prompt cache write, USD per MTok"
    )
    cache_read_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Prompt cache read/hit, USD per MTok"
    )
    batch_input_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Batch API input cost, USD per MTok"
    )
    batch_output_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True, doc="Batch API output cost, USD per MTok"
    )


# ---------------------------------------------------------------------------
# LLM model price history: TTST of pricing snapshots (high-ceremony DB)
# ---------------------------------------------------------------------------

class LlmModelPriceHistory(TemporalMixin, Base):
    """
    Transaction-time system table of LLM model pricing.

    Tracks pricing changes over time using sys_from/sys_to (from TemporalMixin).
    The current price for a model is the row where sys_to IS NULL.

    Snapshot workflow:
      1. Fetch current prices from Bifrost /v1/models (or YAML fallback)
      2. Compare each model against the current row (sys_to IS NULL)
      3. If prices differ: close the old row (sys_to = now), insert new row
      4. If prices match: no-op (idempotent)

    sys_from is an upper bound on when the price actually changed — the
    real change happened between this snapshot and the previous one.

    Lives on PostgreSQL/SQL Server — the persistent catalog, not a session
    table.
    """

    __tablename__ = "llm_model_price_history"

    price_history_id: Mapped[int] = mapped_column(
        Integer, Identity(), primary_key=True
    )
    model: Mapped[str] = mapped_column(
        String(200), doc="Provider-prefixed model ID, e.g. anthropic/claude-sonnet-4-6"
    )
    input_per_mtok: Mapped[float] = mapped_column(Float)
    output_per_mtok: Mapped[float] = mapped_column(Float)
    cache_write_5m_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    cache_write_1h_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    cache_read_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    batch_input_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )
    batch_output_per_mtok: Mapped[float | None] = mapped_column(
        Float, nullable=True
    )

    __table_args__ = (
        # Only one current row per model (partial unique index on PG,
        # enforced by application logic on SQL Server)
        Index("ix_price_history_model", "model"),
        Index("ix_price_history_current", "model", "sys_to"),
    )
